package zad1;



import java.util.ListResourceBundle;

public class Info_pl_PL extends ListResourceBundle{

	@Override
	public Object[][] getContents() {
		// TODO Auto-generated method stub
		return contents;
	}

	private Object [][] contents = {
			

			
			{"Malta", " Malta"},
			{"Wenezuela", " Wenezuela"},
			{"Tajwan", " Tajwan"},
			{"Dania", " Dania"},
			{"Portoryko", " Portoryko"},
			{"Wietnam", " Wietnam"},
			{"Stany Zjednoczone Ameryki", " Stany Zjednoczone Ameryki"},
			{"Montenegro", " Montenegro"},
			{"Szwecja", " Szwecja"},
			{"Boliwia", " Boliwia"},
			{"Singapur", " Singapur"},
			{"Bahrajn", " Bahrajn"},
			{"Arabia Saudyjska", " Arabia Saudyjska"},
			{"Jemen", " Jemen"},
			{"Indie", " Indie"},
			{"Malta", " Malta"},
			{"Finlandia", " Finlandia"},
			{"Bośnia i Hercegowina", " Bośnia i Hercegowina"},
			{"Ukraina", " Ukraina"},
			{"Szwajcaria", " Szwajcaria"},
			{"Argentyna", " Argentyna"},
			{"Egipt", " Egipt"},
			{"Japonia", " Japonia"},
			{"Salwador", " Salwador"},
			{"Brazylia", " Brazylia"},
			{"Islandia", " Islandia"},
			{"Republika Czeska", " Republika Czeska"},
			{"Polska", " Polska"},
			{"Hiszpania", " Hiszpania"},
			{"Serbia and Montenegro", " Serbia and Montenegro"},
			{"Malezja", " Malezja"},
			{"Hiszpania", " Hiszpania"},
			{"Kolumbia", " Kolumbia"},
			{"Bułgaria", " Bułgaria"},
			{"Bośnia i Hercegowina", " Bośnia i Hercegowina"},
			{"Paragwaj", " Paragwaj"},
			{"Ekwador", " Ekwador"},
			{"Stany Zjednoczone Ameryki", " Stany Zjednoczone Ameryki"},
			{"Sudan", " Sudan"},
			{"Rumunia", " Rumunia"},
			{"Filipiny", " Filipiny"},
			{"Tunezja", " Tunezja"},
			{"Montenegro", " Montenegro"},
			{"Gwatemala", " Gwatemala"},
			{"Korea Południowa", " Korea Południowa"},
			{"Cypr", " Cypr"},
			{"Meksyk", " Meksyk"},
			{"Rosja", " Rosja"},
			{"Honduras", " Honduras"},
			{"Hong Kong", " Hong Kong"},
			{"Norwegia", " Norwegia"},
			{"Węgry", " Węgry"},
			{"Tajlandia", " Tajlandia"},
			{"Irak", " Irak"},
			{"Chile", " Chile"},
			{"Maroko", " Maroko"},
			{"Irlandia", " Irlandia"},
			{"Turcja", " Turcja"},
			{"Estonia", " Estonia"},
			{"Katar", " Katar"},
			{"Portugalia", " Portugalia"},
			{"Luksemburg", " Luksemburg"},
			{"Oman", " Oman"},
			{"Albania", " Albania"},
			{"Republika Dominikany", " Republika Dominikany"},
			{"Kuba", " Kuba"},
			{"Nowa Zelandia", " Nowa Zelandia"},
			{"Serbia", " Serbia"},
			{"Szwajcaria", " Szwajcaria"},
			{"Urugwaj", " Urugwaj"},
			{"Grecja", " Grecja"},
			{"Izrael", " Izrael"},
			{"Republika Południowej Afryki", " Republika Południowej Afryki"},
			
			{"Japonia" , "Japonia"},
			{"Japan", "Japonia"},
			//{" ", "Japonia"},
			{"Włochy", "Włochy"},
			{"Italy", "Włochy"},
			{"Italien", "Włochy"},
			{"Stany Zjednoczone", "Stany Zjednoczone"},
			{"United States", "Stany Zjednoczone"},
			{"Vereinigte Staaten", "Stany Zjednoczone"},
			{"Zjednoczone Emiraty Arabskie", " Zjednoczone Emiraty Arabskie"},
			{"Jordan", " Jordan"},
			{"Syria", " Syria"},
			{"Chorwacja", " Chorwacja"},
			{"Belgia", " Belgia"},
			{"Panama", " Panama"},
			{"Vereinigte Arabische Emirate", " Zjednoczone Emiraty Arabskie"},
			{"Jordanien", " Jordan"},
			{"Syrien", " Syria"},
			{"Kroatien", " Chorwacja"},
			{"Belgien", " Belgia"},
			{"Panama", " Panama"},
			{"Malta", " Malta"},
			{"Venezuela", " Wenezuela"},
			{"Taiwan", " Tajwan"},
			{"Dänemark", " Dania"},
			{"Puerto Rico", " Portoryko"},
			{"Vietnam", " Wietnam"},
			{"Vereinigte Staaten von Amerika", " Stany Zjednoczone Ameryki"},
			{"Montenegro", " Montenegro"},
			{"Schweden", " Szwecja"},
			{"Bolivien", " Boliwia"},
			{"Singapur", " Singapur"},
			{"Bahrain", " Bahrajn"},
			{"Saudi-Arabien", " Arabia Saudyjska"},
			{"Jemen", " Jemen"},
			{"Indien", " Indie"},
			{"Malta", " Malta"},
			{"Finnland", " Finlandia"},
			{"Bosnien und Herzegowina", " Bośnia i Hercegowina"},
			{"Ukraine", " Ukraina"},
			{"Schweiz", " Szwajcaria"},
			{"Argentinien", " Argentyna"},
			{"Ägypten", " Egipt"},
			{"Japan", " Japonia"},
			{"El Salvador", " Salwador"},
			{"Brasilien", " Brazylia"},
			{"Island", " Islandia"},
			{"Tschechische Republik", " Republika Czeska"},
			{"Polen", " Polska"},
			{"Spanien", " Hiszpania"},
			{"Serbien und Montenegro", " Serbia and Montenegro"},
			{"Malaysia", " Malezja"},
			{"Spanien", " Hiszpania"},
			{"Kolumbien", " Kolumbia"},
			{"Bulgarien", " Bułgaria"},
			{"Bosnien und Herzegowina", " Bośnia i Hercegowina"},
			{"Paraguay", " Paragwaj"},
			{"Ecuador", " Ekwador"},
			{"Vereinigte Staaten von Amerika", " Stany Zjednoczone Ameryki"},
			{"Sudan", " Sudan"},
			{"Rumänien", " Rumunia"},
			{"Philippinen", " Filipiny"},
			{"Tunesien", " Tunezja"},
			{"Montenegro", " Montenegro"},
			{"Guatemala", " Gwatemala"},
			{"Südkorea", " Korea Południowa"},
			{"Zypern", " Cypr"},
		
			{"Irak", " Irak"},
			{"Chile", " Chile"},
			{"Marokko", " Maroko"},
			{"Irland", " Irlandia"},
			{"Türkei", " Turcja"},
			{"Estland", " Estonia"},
			{"Katar", " Katar"},
			{"Portugal", " Portugalia"},
			{"Luxemburg", " Luksemburg"},
			{"Oman", " Oman"},
			{"Albanien", " Albania"},
	
			{"Griechenland", " Grecja"},
			{"Israel", " Izrael"},
			{"Südafrika", " Republika Południowej Afryki"},
			{"Venezuela", " Wenezuela"},
			{"Taiwan", " Tajwan"},
			{"Denmark", " Dania"},
			{"Puerto Rico", " Portoryko"},
			{"Vietnam", " Wietnam"},
			{"United States", " Stany Zjednoczone Ameryki"},
			
			{"United Arab Emirates", " Zjednoczone Emiraty Arabskie"},
			{"Jordan", " Jordan"},
			{"Syria", " Syria"},
			{"Croatia", " Chorwacja"},
			{"Belgium", " Belgia"},
			{"Panama", " Panama"},
			{"Malta", " Malta"},
		
			{"Montenegro", " Montenegro"},
			{"Sweden", " Szwecja"},
			{"Bolivia", " Boliwia"},
			{"El Salvador", " Salwador"},
			{"Brazil", " Brazylia"},
			{"Iceland", " Islandia"},
			{"Czech Republic", " Republika Czeska"},
			{"Poland", " Polska"},
			{"Spain", " Hiszpania"},
			{"Serbia and Montenegro", " Serbia and Montenegro"},
			{"Singapore", " Singapur"},
			{"Bahrain", " Bahrajn"},
			{"Saudi Arabia", " Arabia Saudyjska"},
			{"Yemen", " Jemen"},
			{"India", " Indie"},
			{"Malta", " Malta"},
			{"Finland", " Finlandia"},
			{"Bosnia and Herzegovina", " Bośnia i Hercegowina"},
			{"Ukraine", " Ukraina"},
			{"Switzerland", " Szwajcaria"},
			{"Argentina", " Argentyna"},
			{"Egypt", " Egipt"},
			{"Japan", " Japonia"},
	
			{"Malaysia", " Malezja"},
			{"Spain", " Hiszpania"},
			{"Colombia", " Kolumbia"},
			{"Serbia", " Serbia"},
			{"Switzerland", " Szwajcaria"},
			{"Uruguay", " Urugwaj"},
			{"Greece", " Grecja"},
			{"Bulgaria", " Bułgaria"},
			{"Bosnia and Herzegovina", " Bośnia i Hercegowina"},
			{"Paraguay", " Paragwaj"},
			{"Ecuador", " Ekwador"},
			{"United States", " Stany Zjednoczone Ameryki"},
			{"Sudan", " Sudan"},
			{"Romania", " Rumunia"},
			{"Philippines", " Filipiny"},
			{"Tunisia", " Tunezja"},
			{"Montenegro", " Montenegro"},
			{"Guatemala", " Gwatemala"},
			{"South Korea", " Korea Południowa"},
			{"Cyprus", " Cypr"},
			{"Mexico", " Meksyk"},
			{"Russia", " Rosja"},
			{"Honduras", " Honduras"},
			{"Dominican Republic", " Republika Dominikany"},
			{"Cuba", " Kuba"},
			{"New Zealand", " Nowa Zelandia"},
		
			{"Israel", " Izrael"},
			{"South Africa", " Republika Południowej Afryki"},
			{"Hong Kong", " Hong Kong"},
			{"Norway", " Norwegia"},
			{"Hungary", " Węgry"},
			{"Thailand", " Tajlandia"},
			{"Iraq", " Irak"},
			{"Chile", " Chile"},
			{"Morocco", " Maroko"},
			{"Ireland", " Irlandia"},
			{"Turkey", " Turcja"},
			{"Estonia", " Estonia"},
			{"Qatar", " Katar"},
			{"Portugal", " Portugalia"},
			{"Luxembourg", " Luksemburg"},
			{"Oman", " Oman"},
			{"Albania", " Albania"},
			{"Dominikanische Republik", " Republika Dominikany"},
			{"Kuba", " Kuba"},
			{"Neuseeland", " Nowa Zelandia"},
			{"Serbien", " Serbia"},
			{"Schweiz", " Szwajcaria"},
			{"Uruguay", " Urugwaj"},
			{"Mexiko", " Meksyk"},
			{"Russland", " Rosja"},
			{"Honduras", " Honduras"},
			{"Hongkong", " Hong Kong"},
			{"Norwegen", " Norwegia"},
			{"Ungarn", " Węgry"},
			{"Thailand", " Tajlandia"},

			{"jezioro", "jezioro"},
			{"lake", "jezioro"},
			{"see", "jezioro"},
			{"morze", "morze"},
			{"sea", "morze"},
			{"meer", "morze"},
			{"góry", "góry"},
			{"mountains", "góry"},
			{"blutrünstig", "góry"}
			
			
			
	};
}
