package zad1;



	import java.util.ListResourceBundle;

	public class Info_en_GB extends ListResourceBundle{

		@Override
		public Object[][] getContents() {
			// TODO Auto-generated method stub
			return contents;
		}
		
		private Object[][] contents ={
				{"Zjednoczone Emiraty Arabskie", " United Arab Emirates"},
				{"Jordan", " Jordan"},
				{"Syria", " Syria"},
				{"Chorwacja", " Croatia"},
				{"Belgia", " Belgium"},
				{"Panama", " Panama"},
				{"Malta", " Malta"},
				{"Wenezuela", " Venezuela"},
				{"Tajwan", " Taiwan"},
				{"Dania", " Denmark"},
				{"Portoryko", " Puerto Rico"},
				{"Wietnam", " Vietnam"},
				{"Stany Zjednoczone Ameryki", " United States"},
				{"Montenegro", " Montenegro"},
				{"Szwecja", " Sweden"},
				{"Boliwia", " Bolivia"},
				{"Singapur", " Singapore"},
				{"Bahrajn", " Bahrain"},
				{"Arabia Saudyjska", " Saudi Arabia"},
				{"Jemen", " Yemen"},
				{"Indie", " India"},
				{"Malta", " Malta"},
				{"Finlandia", " Finland"},
				{"Bośnia i Hercegowina", " Bosnia and Herzegovina"},
				{"Ukraina", " Ukraine"},
				{"Szwajcaria", " Switzerland"},
				{"Argentyna", " Argentina"},
				{"Egipt", " Egypt"},
				{"Japonia", " Japan"},
				{"Salwador", " El Salvador"},
				{"Brazylia", " Brazil"},
				{"Islandia", " Iceland"},
				{"Republika Czeska", " Czech Republic"},
				{"Polska", " Poland"},
				{"Hiszpania", " Spain"},
				{"Serbia and Montenegro", " Serbia and Montenegro"},
				{"Malezja", " Malaysia"},
				{"Hiszpania", " Spain"},
				{"Kolumbia", " Colombia"},
				{"Bułgaria", " Bulgaria"},
				{"Bośnia i Hercegowina", " Bosnia and Herzegovina"},
				{"Paragwaj", " Paraguay"},
				{"Ekwador", " Ecuador"},
				{"Stany Zjednoczone Ameryki", " United States"},
				{"Sudan", " Sudan"},
				{"Rumunia", " Romania"},
				{"Filipiny", " Philippines"},
				{"Tunezja", " Tunisia"},
				{"Montenegro", " Montenegro"},
				{"Gwatemala", " Guatemala"},
				{"Korea Południowa", " South Korea"},
				{"Cypr", " Cyprus"},
				{"Meksyk", " Mexico"},
				{"Rosja", " Russia"},
				{"Honduras", " Honduras"},
				{"Hong Kong", " Hong Kong"},
				{"Norwegia", " Norway"},
				{"Węgry", " Hungary"},
				{"Tajlandia", " Thailand"},
				{"Irak", " Iraq"},
				{"Chile", " Chile"},
				{"Maroko", " Morocco"},
				{"Irlandia", " Ireland"},
				{"Turcja", " Turkey"},
				{"Estonia", " Estonia"},
				{"Katar", " Qatar"},
				{"Portugalia", " Portugal"},
				{"Luksemburg", " Luxembourg"},
				{"Oman", " Oman"},
				{"Albania", " Albania"},
				{"Republika Dominikany", " Dominican Republic"},
				{"Kuba", " Cuba"},
				{"Nowa Zelandia", " New Zealand"},
				{"Serbia", " Serbia"},
				{"Szwajcaria", " Switzerland"},
				{"Urugwaj", " Uruguay"},
				{"Grecja", " Greece"},
				{"Izrael", " Israel"},
				{"Republika Południowej Afryki", " South Africa"},
				
				
				{"United Arab Emirates", " United Arab Emirates"},
				{"Jordan", " Jordan"},
				{"Syria", " Syria"},
				{"Croatia", " Croatia"},
				{"Belgium", " Belgium"},
				{"Panama", " Panama"},
				{"Malta", " Malta"},
				{"Venezuela", " Venezuela"},
				{"Taiwan", " Taiwan"},
				{"Denmark", " Denmark"},
				{"Puerto Rico", " Puerto Rico"},
				{"Vietnam", " Vietnam"},
				{"United States", " United States"},
				{"Montenegro", " Montenegro"},
				{"Sweden", " Sweden"},
				{"Bolivia", " Bolivia"},
				{"Singapore", " Singapore"},
				{"Bahrain", " Bahrain"},
				{"Saudi Arabia", " Saudi Arabia"},
				{"Yemen", " Yemen"},
				{"India", " India"},
				{"Malta", " Malta"},
				{"Finland", " Finland"},
				{"Bosnia and Herzegovina", " Bosnia and Herzegovina"},
				{"Ukraine", " Ukraine"},
				{"Switzerland", " Switzerland"},
				{"Argentina", " Argentina"},
				{"Egypt", " Egypt"},
				{"Japan", " Japan"},
				{"El Salvador", " El Salvador"},
				{"Brazil", " Brazil"},
				{"Iceland", " Iceland"},
				{"Czech Republic", " Czech Republic"},
				{"Poland", " Poland"},
				{"Spain", " Spain"},
				{"Serbia and Montenegro", " Serbia and Montenegro"},
				{"Malaysia", " Malaysia"},
				{"Spain", " Spain"},
				{"Colombia", " Colombia"},
				{"Bulgaria", " Bulgaria"},
				{"Bosnia and Herzegovina", " Bosnia and Herzegovina"},
				{"Paraguay", " Paraguay"},
				{"Ecuador", " Ecuador"},
				{"United States", " United States"},
				{"Sudan", " Sudan"},
				{"Romania", " Romania"},
				{"Philippines", " Philippines"},
				{"Tunisia", " Tunisia"},
				{"Montenegro", " Montenegro"},
				{"Guatemala", " Guatemala"},
				{"South Korea", " South Korea"},
				{"Cyprus", " Cyprus"},
				{"Mexico", " Mexico"},
				{"Russia", " Russia"},
				{"Honduras", " Honduras"},
				{"Hong Kong", " Hong Kong"},
				{"Norway", " Norway"},
				{"Hungary", " Hungary"},
				{"Thailand", " Thailand"},
				{"Iraq", " Iraq"},
				{"Chile", " Chile"},
				{"Morocco", " Morocco"},
				{"Ireland", " Ireland"},
				{"Turkey", " Turkey"},
				{"Estonia", " Estonia"},
				{"Qatar", " Qatar"},
				{"Portugal", " Portugal"},
				{"Luxembourg", " Luxembourg"},
				{"Oman", " Oman"},
				{"Albania", " Albania"},
				{"Dominican Republic", " Dominican Republic"},
				{"Cuba", " Cuba"},
				{"New Zealand", " New Zealand"},
				{"Serbia", " Serbia"},
				{"Switzerland", " Switzerland"},
				{"Uruguay", " Uruguay"},
				{"Greece", " Greece"},
				{"Israel", " Israel"},
				{"South Africa", " South Africa"},
				
				{"Vereinigte Arabische Emirate", " United Arab Emirates"},
				{"Jordanien", " Jordan"},
				{"Syrien", " Syria"},
				{"Kroatien", " Croatia"},
				{"Belgien", " Belgium"},
				{"Panama", " Panama"},
				{"Malta", " Malta"},
				{"Venezuela", " Venezuela"},
				{"Taiwan", " Taiwan"},
				{"Dänemark", " Denmark"},
				{"Puerto Rico", " Puerto Rico"},
				{"Vietnam", " Vietnam"},
				{"Vereinigte Staaten von Amerika", " United States"},
				{"Montenegro", " Montenegro"},
				{"Schweden", " Sweden"},
				{"Bolivien", " Bolivia"},
				{"Singapur", " Singapore"},
				{"Bahrain", " Bahrain"},
				{"Saudi-Arabien", " Saudi Arabia"},
				{"Jemen", " Yemen"},
				{"Indien", " India"},
				{"Malta", " Malta"},
				{"Finnland", " Finland"},
				{"Bosnien und Herzegowina", " Bosnia and Herzegovina"},
				{"Ukraine", " Ukraine"},
				{"Schweiz", " Switzerland"},
				{"Guatemala", " Guatemala"},
				{"Südkorea", " South Korea"},
				{"Zypern", " Cyprus"},
				{"Mexiko", " Mexico"},
				{"Russland", " Russia"},
			
				{"Irak", " Iraq"},
				{"Chile", " Chile"},
				{"Marokko", " Morocco"},
				{"Argentinien", " Argentina"},
				{"Ägypten", " Egypt"},
				{"Japan", " Japan"},
				{"El Salvador", " El Salvador"},
				{"Brasilien", " Brazil"},
				{"Island", " Iceland"},
				{"Tschechische Republik", " Czech Republic"},
				{"Polen", " Poland"},
				{"Spanien", " Spain"},
				{"Serbien und Montenegro", " Serbia and Montenegro"},
				{"Malaysia", " Malaysia"},
				{"Spanien", " Spain"},
				{"Kolumbien", " Colombia"},
				{"Bulgarien", " Bulgaria"},
				{"Bosnien und Herzegowina", " Bosnia and Herzegovina"},
				{"Paraguay", " Paraguay"},
				{"Ecuador", " Ecuador"},
				{"Vereinigte Staaten von Amerika", " United States"},
				{"Sudan", " Sudan"},
				{"Rumänien", " Romania"},
				{"Philippinen", " Philippines"},
				{"Tunesien", " Tunisia"},
				{"Montenegro", " Montenegro"},
				
			
			
				{"Dominikanische Republik", " Dominican Republic"},
				{"Kuba", " Cuba"},
				{"Neuseeland", " New Zealand"},
				{"Serbien", " Serbia"},
				{"Schweiz", " Switzerland"},
				{"Uruguay", " Uruguay"},
				{"Oman", " Oman"},
				{"Albanien", " Albania"},
				{"see", "lake"},
				{"jezioro", "lake"},
				{"mountains", "mountains"},
				{"góry", "mountains"},
				{"blutrünstig", "mountains"},
				{"sea", "sea"},
				{"morze", "sea"},
				{"Griechenland", " Greece"},
				{"Israel", " Israel"},
				{"Südafrika", " South Africa"},
				{"Irland", " Ireland"},
				{"Türkei", " Turkey"},
				{"Estland", " Estonia"},
				{"Katar", " Qatar"},
				{"Portugal", " Portugal"},
				{"Luxemburg", " Luxembourg"},
				
				{"Polska", "Poland"},
				{"Poland", "Poland"},
				{"United States", "United States"},
				{"Stany Zjednoczone", "United States"},
				{"Vereinigte Staaten", "United States"},
				{"Italy", "Italy"},
				{"Włochy", "Italy"},
				{"Italien", "Italy"},
				{"Japan", "Japan"},
				{"Japonia", "Japan"},
				//{"", "Japan"}
				{"lake", "lake"},
				{"Honduras", " Honduras"},
				{"Hongkong", " Hong Kong"},
				{"Norwegen", " Norway"},
				{"Ungarn", " Hungary"},
				{"Thailand", " Thailand"},
		
				{"meer", "sea"}
		};

	}

		
				
				
			

	