package zad1;

import java.util.ListResourceBundle;

public class Info_de_DE extends ListResourceBundle{

	@Override
	public Object[][] getContents() {
		// TODO Auto-generated method stub
		return contents;
	}
	
	private Object [][] contents = {
			
				{"jezioro", "see"},
				{"lake", "see"},
				{"see", "see"},
				{"morze", "meer"},
				{"sea", "meer"},
				{"meer", "meer"},
				{"góry", "blutrünstig"},
				{"mountains", "blutrünstig"},
				{"blutrünstig", "blutrünstig"},
				

				{"Włochy", "Italien"},
				{"Italy", "Italien"},
	{"Zjednoczone Emiraty Arabskie", " Vereinigte Arabische Emirate"},
	{"Jemen", " Jemen"},
	{"Indie", " Indien"},
	{"Malta", " Malta"},
	{"Finlandia", " Finnland"},
	{"Bośnia i Hercegowina", " Bosnien und Herzegowina"},
	{"Ukraina", " Ukraine"},
	{"Szwajcaria", " Schweiz"},
	{"Jordan", " Jordanien"},
	{"Syria", " Syrien"},
	{"Chorwacja", " Kroatien"},
	{"Belgia", " Belgien"},
	{"Panama", " Panama"},
	{"Malta", " Malta"},
	{"Wenezuela", " Venezuela"},
	{"Tajwan", " Taiwan"},
	{"Dania", " Dänemark"},
	{"Portoryko", " Puerto Rico"},
	{"Wietnam", " Vietnam"},
	{"Stany Zjednoczone Ameryki", " Vereinigte Staaten von Amerika"},
	{"Montenegro", " Montenegro"},
	{"Szwecja", " Schweden"},
	{"Boliwia", " Bolivien"},
	{"Singapur", " Singapur"},
	{"Bahrajn", " Bahrain"},
	{"Arabia Saudyjska", " Saudi-Arabien"},

	{"Argentyna", " Argentinien"},
	{"Egipt", " Ägypten"},
	{"Japonia", " Japan"},
	{"Salwador", " El Salvador"},
	{"Brazylia", " Brasilien"},
	{"Islandia", " Island"},
	{"Republika Czeska", " Tschechische Republik"},
	{"Polska", " Polen"},
	{"Hiszpania", " Spanien"},
	{"Serbia and Montenegro", " Serbien und Montenegro"},
	{"Malezja", " Malaysia"},
	{"Hiszpania", " Spanien"},
	{"Kolumbia", " Kolumbien"},
	{"Bułgaria", " Bulgarien"},
	{"Bośnia i Hercegowina", " Bosnien und Herzegowina"},
	{"Paragwaj", " Paraguay"},
	{"Ekwador", " Ecuador"},
	{"Stany Zjednoczone Ameryki", " Vereinigte Staaten von Amerika"},
	{"Sudan", " Sudan"},
	{"Rumunia", " Rumänien"},
	{"Filipiny", " Philippinen"},
	{"Tunezja", " Tunesien"},
	{"Montenegro", " Montenegro"},
	{"Gwatemala", " Guatemala"},
	{"Korea Południowa", " Südkorea"},
	{"Cypr", " Zypern"},
	{"Meksyk", " Mexiko"},
	{"Rosja", " Russland"},
	{"Honduras", " Honduras"},
	{"Hong Kong", " Hongkong"},
	{"Norwegia", " Norwegen"},
	{"Węgry", " Ungarn"},
	{"Tajlandia", " Thailand"},
	{"Irak", " Irak"},
	{"Chile", " Chile"},
	{"Maroko", " Marokko"},
	{"Irlandia", " Irland"},
	{"Turcja", " Türkei"},
	{"Estonia", " Estland"},
	{"Katar", " Katar"},
	{"Portugalia", " Portugal"},
	{"Luksemburg", " Luxemburg"},
	{"Oman", " Oman"},
	{"Albania", " Albanien"},
	{"Republika Dominikany", " Dominikanische Republik"},
	{"Kuba", " Kuba"},
	{"Nowa Zelandia", " Neuseeland"},
	{"Serbia", " Serbien"},
	{"Szwajcaria", " Schweiz"},
	{"Urugwaj", " Uruguay"},
	{"Grecja", " Griechenland"},
	{"Izrael", " Israel"},
	{"Republika Południowej Afryki", " Südafrika"},


	{"Vereinigte Arabische Emirate", " Vereinigte Arabische Emirate"},
	{"Jordanien", " Jordanien"},
	{"Syrien", " Syrien"},
	{"Kroatien", " Kroatien"},
	{"Belgien", " Belgien"},
	{"Panama", " Panama"},
	{"Malta", " Malta"},
	{"Venezuela", " Venezuela"},
	{"Taiwan", " Taiwan"},
	{"Dänemark", " Dänemark"},
	{"Puerto Rico", " Puerto Rico"},
	{"Vietnam", " Vietnam"},
	{"Vereinigte Staaten von Amerika", " Vereinigte Staaten von Amerika"},
	{"Montenegro", " Montenegro"},
	{"Honduras", " Honduras"},
	{"Hongkong", " Hongkong"},
	{"Norwegen", " Norwegen"},
	{"Ungarn", " Ungarn"},
	{"Thailand", " Thailand"},
	{"Irak", " Irak"},
	{"Chile", " Chile"},
	{"Marokko", " Marokko"},
	{"Irland", " Irland"},
	{"Türkei", " Türkei"},
	
	{"Schweden", " Schweden"},
	{"Bolivien", " Bolivien"},
	{"Singapur", " Singapur"},
	{"Bahrain", " Bahrain"},
	{"Saudi-Arabien", " Saudi-Arabien"},
	{"Jemen", " Jemen"},
	{"Indien", " Indien"},
	{"Malta", " Malta"},
	{"Finnland", " Finnland"},
	{"Bosnien und Herzegowina", " Bosnien und Herzegowina"},
	{"Ukraine", " Ukraine"},
	{"Schweiz", " Schweiz"},
	{"Argentinien", " Argentinien"},
	{"Ägypten", " Ägypten"},
	{"Japan", " Japan"},
	{"El Salvador", " El Salvador"},
	{"Brasilien", " Brasilien"},
	{"Island", " Island"},
	{"Tschechische Republik", " Tschechische Republik"},
	{"Polen", " Polen"},
	{"Spanien", " Spanien"},
	{"Serbien und Montenegro", " Serbien und Montenegro"},
	{"Malaysia", " Malaysia"},
	{"Spanien", " Spanien"},
	{"Kolumbien", " Kolumbien"},
	{"Bulgarien", " Bulgarien"},
	{"Bosnien und Herzegowina", " Bosnien und Herzegowina"},
	{"Paraguay", " Paraguay"},
	{"Ecuador", " Ecuador"},
	{"Vereinigte Staaten von Amerika", " Vereinigte Staaten von Amerika"},
	{"Sudan", " Sudan"},
	{"Rumänien", " Rumänien"},
	{"Philippinen", " Philippinen"},
	{"Tunesien", " Tunesien"},
	{"Montenegro", " Montenegro"},
	{"Guatemala", " Guatemala"},
	{"Südkorea", " Südkorea"},
	{"Zypern", " Zypern"},
	{"Mexiko", " Mexiko"},
	{"Russland", " Russland"},
{"Estland", " Estland"},
	{"Katar", " Katar"},
	{"Portugal", " Portugal"},
	{"Luxemburg", " Luxemburg"},
	{"Oman", " Oman"},
	{"Albanien", " Albanien"},
	{"Dominikanische Republik", " Dominikanische Republik"},
	{"Kuba", " Kuba"},
	{"Neuseeland", " Neuseeland"},
	{"Serbien", " Serbien"},
	{"Schweiz", " Schweiz"},
	{"Uruguay", " Uruguay"},
	{"Griechenland", " Griechenland"},
	{"Israel", " Israel"},
	{"Südafrika", " Südafrika"},

	{"United Arab Emirates", " Vereinigte Arabische Emirate"},
	{"Jordan", " Jordanien"},
	{"Syria", " Syrien"},
	{"Croatia", " Kroatien"},
	{"Belgium", " Belgien"},
	{"Panama", " Panama"},
	{"Malta", " Malta"},
	{"Venezuela", " Venezuela"},
	{"Taiwan", " Taiwan"},
	{"Denmark", " Dänemark"},
	{"Puerto Rico", " Puerto Rico"},
		{"Saudi Arabia", " Saudi-Arabien"},
	{"Yemen", " Jemen"},
	{"India", " Indien"},
	{"Malta", " Malta"},
	{"Spain", " Spanien"},
	{"Colombia", " Kolumbien"},
	{"Bulgaria", " Bulgarien"},
	{"Bosnia and Herzegovina", " Bosnien und Herzegowina"},
	{"Paraguay", " Paraguay"},
	{"Ecuador", " Ecuador"},
	{"United States", " Vereinigte Staaten von Amerika"},
	{"Sudan", " Sudan"},
	{"Romania", " Rumänien"},
	{"Philippines", " Philippinen"},
	{"Tunisia", " Tunesien"},
	{"Montenegro", " Montenegro"},
	{"Finland", " Finnland"},
	{"Bosnia and Herzegovina", " Bosnien und Herzegowina"},
	{"Ukraine", " Ukraine"},
	{"Switzerland", " Schweiz"},
	{"Argentina", " Argentinien"},
	{"Egypt", " Ägypten"},
	{"Japan", " Japan"},
	{"El Salvador", " El Salvador"},
	{"Brazil", " Brasilien"},
	{"Iceland", " Island"},
	{"Czech Republic", " Tschechische Republik"},
	{"Poland", " Polen"},
	{"Spain", " Spanien"},
	{"Serbia and Montenegro", " Serbien und Montenegro"},
	{"Malaysia", " Malaysia"},

	{"Guatemala", " Guatemala"},
	{"South Korea", " Südkorea"},
	{"Cyprus", " Zypern"},
	{"Mexico", " Mexiko"},
	{"Russia", " Russland"},
	{"Honduras", " Honduras"},
	{"Hong Kong", " Hongkong"},
	{"Norway", " Norwegen"},
	{"Albania", " Albanien"},
	{"Dominican Republic", " Dominikanische Republik"},
	{"Cuba", " Kuba"},
	{"New Zealand", " Neuseeland"},
	{"Serbia", " Serbien"},
	{"Switzerland", " Schweiz"},
	{"Uruguay", " Uruguay"},
	{"Greece", " Griechenland"},
	{"Israel", " Israel"},
	{"South Africa", " Südafrika"},
	{"Vietnam", " Vietnam"},
	{"United States", " Vereinigte Staaten von Amerika"},
	{"Montenegro", " Montenegro"},
	{"Sweden", " Schweden"},
	{"Bolivia", " Bolivien"},
	{"Singapore", " Singapur"},
	{"Bahrain", " Bahrain"},

	{"Hungary", " Ungarn"},
	{"Thailand", " Thailand"},
	{"Iraq", " Irak"},
	{"Chile", " Chile"},
	{"Morocco", " Marokko"},
	{"Ireland", " Irland"},
	{"Turkey", " Türkei"},
	{"Estonia", " Estland"},
	{"Qatar", " Katar"},
	{"Portugal", " Portugal"},
	{"Luxembourg", " Luxemburg"},
	{"Oman", " Oman"},
	

				
		};

}